version: '3.3'

services:

  app:
    image: ${IMAGE:-app}
    ports:
      - "10010:10010"  
    depends_on:
      - postgres
      
    environment:
      - GRPC_PORT=10010
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=test

  postgres:
    image: timescale/timescaledb:2.12.2-pg15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test
    # ports:
    #   - "5432:5432"
