// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.21.12
// source: protos/monitor.proto

package protos

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ZoneMonitor_MonitorZoneV1_FullMethodName = "/location.engine.protos.ZoneMonitor/MonitorZoneV1"
)

// ZoneMonitorClient is the client API for ZoneMonitor service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ZoneMonitorClient interface {
	MonitorZoneV1(ctx context.Context, in *MonitorZoneRequestV1, opts ...grpc.CallOption) (grpc.ServerStreamingClient[MonitorZoneStreamEventV1], error)
}

type zoneMonitorClient struct {
	cc grpc.ClientConnInterface
}

func NewZoneMonitorClient(cc grpc.ClientConnInterface) ZoneMonitorClient {
	return &zoneMonitorClient{cc}
}

func (c *zoneMonitorClient) MonitorZoneV1(ctx context.Context, in *MonitorZoneRequestV1, opts ...grpc.CallOption) (grpc.ServerStreamingClient[MonitorZoneStreamEventV1], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ZoneMonitor_ServiceDesc.Streams[0], ZoneMonitor_MonitorZoneV1_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[MonitorZoneRequestV1, MonitorZoneStreamEventV1]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ZoneMonitor_MonitorZoneV1Client = grpc.ServerStreamingClient[MonitorZoneStreamEventV1]

// ZoneMonitorServer is the server API for ZoneMonitor service.
// All implementations must embed UnimplementedZoneMonitorServer
// for forward compatibility.
type ZoneMonitorServer interface {
	MonitorZoneV1(*MonitorZoneRequestV1, grpc.ServerStreamingServer[MonitorZoneStreamEventV1]) error
	mustEmbedUnimplementedZoneMonitorServer()
}

// UnimplementedZoneMonitorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedZoneMonitorServer struct{}

func (UnimplementedZoneMonitorServer) MonitorZoneV1(*MonitorZoneRequestV1, grpc.ServerStreamingServer[MonitorZoneStreamEventV1]) error {
	return status.Error(codes.Unimplemented, "method MonitorZoneV1 not implemented")
}
func (UnimplementedZoneMonitorServer) mustEmbedUnimplementedZoneMonitorServer() {}
func (UnimplementedZoneMonitorServer) testEmbeddedByValue()                     {}

// UnsafeZoneMonitorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ZoneMonitorServer will
// result in compilation errors.
type UnsafeZoneMonitorServer interface {
	mustEmbedUnimplementedZoneMonitorServer()
}

func RegisterZoneMonitorServer(s grpc.ServiceRegistrar, srv ZoneMonitorServer) {
	// If the following call panics, it indicates UnimplementedZoneMonitorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ZoneMonitor_ServiceDesc, srv)
}

func _ZoneMonitor_MonitorZoneV1_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(MonitorZoneRequestV1)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ZoneMonitorServer).MonitorZoneV1(m, &grpc.GenericServerStream[MonitorZoneRequestV1, MonitorZoneStreamEventV1]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ZoneMonitor_MonitorZoneV1Server = grpc.ServerStreamingServer[MonitorZoneStreamEventV1]

// ZoneMonitor_ServiceDesc is the grpc.ServiceDesc for ZoneMonitor service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ZoneMonitor_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "location.engine.protos.ZoneMonitor",
	HandlerType: (*ZoneMonitorServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "MonitorZoneV1",
			Handler:       _ZoneMonitor_MonitorZoneV1_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "protos/monitor.proto",
}
