// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: protos/monitor.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MonitorZoneRequestV1 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrgId         string                 `protobuf:"bytes,1,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	MapId         string                 `protobuf:"bytes,2,opt,name=map_id,json=mapId,proto3" json:"map_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MonitorZoneRequestV1) Reset() {
	*x = MonitorZoneRequestV1{}
	mi := &file_protos_monitor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MonitorZoneRequestV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MonitorZoneRequestV1) ProtoMessage() {}

func (x *MonitorZoneRequestV1) ProtoReflect() protoreflect.Message {
	mi := &file_protos_monitor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MonitorZoneRequestV1.ProtoReflect.Descriptor instead.
func (*MonitorZoneRequestV1) Descriptor() ([]byte, []int) {
	return file_protos_monitor_proto_rawDescGZIP(), []int{0}
}

func (x *MonitorZoneRequestV1) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *MonitorZoneRequestV1) GetMapId() string {
	if x != nil {
		return x.MapId
	}
	return ""
}

type MonitorZoneStreamEventV1 struct {
	state         protoimpl.MessageState                  `protogen:"open.v1"`
	Event         []*MonitorZoneStreamEventV1_ZoneEventV1 `protobuf:"bytes,1,rep,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MonitorZoneStreamEventV1) Reset() {
	*x = MonitorZoneStreamEventV1{}
	mi := &file_protos_monitor_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MonitorZoneStreamEventV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MonitorZoneStreamEventV1) ProtoMessage() {}

func (x *MonitorZoneStreamEventV1) ProtoReflect() protoreflect.Message {
	mi := &file_protos_monitor_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MonitorZoneStreamEventV1.ProtoReflect.Descriptor instead.
func (*MonitorZoneStreamEventV1) Descriptor() ([]byte, []int) {
	return file_protos_monitor_proto_rawDescGZIP(), []int{1}
}

func (x *MonitorZoneStreamEventV1) GetEvent() []*MonitorZoneStreamEventV1_ZoneEventV1 {
	if x != nil {
		return x.Event
	}
	return nil
}

type MonitorZoneStreamEventV1_ZoneEventV1 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ZoneId        string                 `protobuf:"bytes,1,opt,name=zone_id,json=zoneId,proto3" json:"zone_id,omitempty"`
	ZoneName      string                 `protobuf:"bytes,2,opt,name=zone_name,json=zoneName,proto3" json:"zone_name,omitempty"`
	MapId         string                 `protobuf:"bytes,3,opt,name=map_id,json=mapId,proto3" json:"map_id,omitempty"`
	OrgId         string                 `protobuf:"bytes,4,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	PositionX     float32                `protobuf:"fixed32,5,opt,name=positionX,proto3" json:"positionX,omitempty"`
	PositionY     float32                `protobuf:"fixed32,6,opt,name=positionY,proto3" json:"positionY,omitempty"`
	Width         float32                `protobuf:"fixed32,7,opt,name=width,proto3" json:"width,omitempty"`
	Height        float32                `protobuf:"fixed32,8,opt,name=height,proto3" json:"height,omitempty"`
	Type          string                 `protobuf:"bytes,9,opt,name=type,proto3" json:"type,omitempty"`
	Info          map[string]string      `protobuf:"bytes,10,rep,name=info,proto3" json:"info,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MonitorZoneStreamEventV1_ZoneEventV1) Reset() {
	*x = MonitorZoneStreamEventV1_ZoneEventV1{}
	mi := &file_protos_monitor_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MonitorZoneStreamEventV1_ZoneEventV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MonitorZoneStreamEventV1_ZoneEventV1) ProtoMessage() {}

func (x *MonitorZoneStreamEventV1_ZoneEventV1) ProtoReflect() protoreflect.Message {
	mi := &file_protos_monitor_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MonitorZoneStreamEventV1_ZoneEventV1.ProtoReflect.Descriptor instead.
func (*MonitorZoneStreamEventV1_ZoneEventV1) Descriptor() ([]byte, []int) {
	return file_protos_monitor_proto_rawDescGZIP(), []int{1, 0}
}

func (x *MonitorZoneStreamEventV1_ZoneEventV1) GetZoneId() string {
	if x != nil {
		return x.ZoneId
	}
	return ""
}

func (x *MonitorZoneStreamEventV1_ZoneEventV1) GetZoneName() string {
	if x != nil {
		return x.ZoneName
	}
	return ""
}

func (x *MonitorZoneStreamEventV1_ZoneEventV1) GetMapId() string {
	if x != nil {
		return x.MapId
	}
	return ""
}

func (x *MonitorZoneStreamEventV1_ZoneEventV1) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *MonitorZoneStreamEventV1_ZoneEventV1) GetPositionX() float32 {
	if x != nil {
		return x.PositionX
	}
	return 0
}

func (x *MonitorZoneStreamEventV1_ZoneEventV1) GetPositionY() float32 {
	if x != nil {
		return x.PositionY
	}
	return 0
}

func (x *MonitorZoneStreamEventV1_ZoneEventV1) GetWidth() float32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *MonitorZoneStreamEventV1_ZoneEventV1) GetHeight() float32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *MonitorZoneStreamEventV1_ZoneEventV1) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *MonitorZoneStreamEventV1_ZoneEventV1) GetInfo() map[string]string {
	if x != nil {
		return x.Info
	}
	return nil
}

var File_protos_monitor_proto protoreflect.FileDescriptor

const file_protos_monitor_proto_rawDesc = "" +
	"\n" +
	"\x14protos/monitor.proto\x12\x16location.engine.protos\"D\n" +
	"\x14MonitorZoneRequestV1\x12\x15\n" +
	"\x06org_id\x18\x01 \x01(\tR\x05orgId\x12\x15\n" +
	"\x06map_id\x18\x02 \x01(\tR\x05mapId\"\xf5\x03\n" +
	"\x18MonitorZoneStreamEventV1\x12R\n" +
	"\x05event\x18\x01 \x03(\v2<.location.engine.protos.MonitorZoneStreamEventV1.ZoneEventV1R\x05event\x1a\x84\x03\n" +
	"\vZoneEventV1\x12\x17\n" +
	"\azone_id\x18\x01 \x01(\tR\x06zoneId\x12\x1b\n" +
	"\tzone_name\x18\x02 \x01(\tR\bzoneName\x12\x15\n" +
	"\x06map_id\x18\x03 \x01(\tR\x05mapId\x12\x15\n" +
	"\x06org_id\x18\x04 \x01(\tR\x05orgId\x12\x1c\n" +
	"\tpositionX\x18\x05 \x01(\x02R\tpositionX\x12\x1c\n" +
	"\tpositionY\x18\x06 \x01(\x02R\tpositionY\x12\x14\n" +
	"\x05width\x18\a \x01(\x02R\x05width\x12\x16\n" +
	"\x06height\x18\b \x01(\x02R\x06height\x12\x12\n" +
	"\x04type\x18\t \x01(\tR\x04type\x12Z\n" +
	"\x04info\x18\n" +
	" \x03(\v2F.location.engine.protos.MonitorZoneStreamEventV1.ZoneEventV1.InfoEntryR\x04info\x1a7\n" +
	"\tInfoEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012\x82\x01\n" +
	"\vZoneMonitor\x12s\n" +
	"\rMonitorZoneV1\x12,.location.engine.protos.MonitorZoneRequestV1\x1a0.location.engine.protos.MonitorZoneStreamEventV1\"\x000\x01BFZDgithub.com/Shuv1Wolf/subterra-locate/services/location-engine/protosb\x06proto3"

var (
	file_protos_monitor_proto_rawDescOnce sync.Once
	file_protos_monitor_proto_rawDescData []byte
)

func file_protos_monitor_proto_rawDescGZIP() []byte {
	file_protos_monitor_proto_rawDescOnce.Do(func() {
		file_protos_monitor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protos_monitor_proto_rawDesc), len(file_protos_monitor_proto_rawDesc)))
	})
	return file_protos_monitor_proto_rawDescData
}

var file_protos_monitor_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_protos_monitor_proto_goTypes = []any{
	(*MonitorZoneRequestV1)(nil),                 // 0: location.engine.protos.MonitorZoneRequestV1
	(*MonitorZoneStreamEventV1)(nil),             // 1: location.engine.protos.MonitorZoneStreamEventV1
	(*MonitorZoneStreamEventV1_ZoneEventV1)(nil), // 2: location.engine.protos.MonitorZoneStreamEventV1.ZoneEventV1
	nil, // 3: location.engine.protos.MonitorZoneStreamEventV1.ZoneEventV1.InfoEntry
}
var file_protos_monitor_proto_depIdxs = []int32{
	2, // 0: location.engine.protos.MonitorZoneStreamEventV1.event:type_name -> location.engine.protos.MonitorZoneStreamEventV1.ZoneEventV1
	3, // 1: location.engine.protos.MonitorZoneStreamEventV1.ZoneEventV1.info:type_name -> location.engine.protos.MonitorZoneStreamEventV1.ZoneEventV1.InfoEntry
	0, // 2: location.engine.protos.ZoneMonitor.MonitorZoneV1:input_type -> location.engine.protos.MonitorZoneRequestV1
	1, // 3: location.engine.protos.ZoneMonitor.MonitorZoneV1:output_type -> location.engine.protos.MonitorZoneStreamEventV1
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_protos_monitor_proto_init() }
func file_protos_monitor_proto_init() {
	if File_protos_monitor_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protos_monitor_proto_rawDesc), len(file_protos_monitor_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_monitor_proto_goTypes,
		DependencyIndexes: file_protos_monitor_proto_depIdxs,
		MessageInfos:      file_protos_monitor_proto_msgTypes,
	}.Build()
	File_protos_monitor_proto = out.File
	file_protos_monitor_proto_goTypes = nil
	file_protos_monitor_proto_depIdxs = nil
}
