---
# Container descriptor
- descriptor: "pip-services:context-info:default:default:1.0"
  name: "service-location-engine"
  description: "Location engine service"

# Console logger
- descriptor: "pip-services:logger:console:default:1.0"
  level: "trace"

# Performance log counters
- descriptor: "pip-services:counters:log:default:1.0"

# NATS raw ble listener
- descriptor: "location-engine:listener:nats:ble-raw-rssi:1.0"
  subject: "events.ble.raw.rssi"
  connection:
    uri:  {{NATS_SERVICE_URI}}
    host: {{NATS_SERVICE_HOST}}{{#unless NATS_SERVICE_HOST}}"localhost"{{/unless}}
    port: {{NATS_SERVICE_PORT}}{{#unless NATS_SERVICE_PORT}}4222{{/unless}}
  credential:
    username: {{NATS_USER}}
    password: {{NATS_PASS}}
  options:
    autosubscribe: true

# NATS device position publisher
- descriptor: "location-engine:publisher:nats:device-position:1.0"
  subject: "events.device.position"
  connection:
    uri:  {{NATS_SERVICE_URI}}
    host: {{NATS_SERVICE_HOST}}{{#unless NATS_SERVICE_HOST}}"localhost"{{/unless}}
    port: {{NATS_SERVICE_PORT}}{{#unless NATS_SERVICE_PORT}}4222{{/unless}}
  credential:
    username: {{NATS_USER}}
    password: {{NATS_PASS}}
  options:
    autosubscribe: true

# NATS beacons event listener
- descriptor: "location-engine:listener:nats:beacons-events:1.0"
  subject: "beacons.events"
  connection:
    uri:  {{NATS_SERVICE_URI}}
    host: {{NATS_SERVICE_HOST}}{{#unless NATS_SERVICE_HOST}}"localhost"{{/unless}}
    port: {{NATS_SERVICE_PORT}}{{#unless NATS_SERVICE_PORT}}4222{{/unless}}
  credential:
    username: {{NATS_USER}}
    password: {{NATS_PASS}}
  options:
    autosubscribe: true

# NATS device event listener
- descriptor: "location-engine:listener:nats:device-events:1.0"
  subject: "device.events"
  connection:
    uri:  {{NATS_SERVICE_URI}}
    host: {{NATS_SERVICE_HOST}}{{#unless NATS_SERVICE_HOST}}"localhost"{{/unless}}
    port: {{NATS_SERVICE_PORT}}{{#unless NATS_SERVICE_PORT}}4222{{/unless}}
  credential:
    username: {{NATS_USER}}
    password: {{NATS_PASS}}
  options:
    autosubscribe: true

# Beacon-admin client
{{^MOCK}}
- descriptor: "beacon-admin:client:grpc:default:1.0"
  connection:
    protocol: "http"
    host: {{BEACON_ADMIN_SERVICE_HOST}}{{^BEACON_ADMIN_SERVICE_HOST}}"localhost"{{/BEACON_ADMIN_SERVICE_HOST}}
    port: {{BEACON_ADMIN_SERVICE_PORT}}{{^BEACON_ADMIN_SERVICE_PORT}}10010{{/BEACON_ADMIN_SERVICE_PORT}}
{{/MOCK}}
{{#if MOCK}}
- descriptor: "beacon-admin:client:mock:default:1.0"
{{/if}}

# Device-admin client
{{^MOCK}}
- descriptor: "device-admin:client:grpc:default:1.0"
  connection:
    protocol: "http"
    host: {{DEVICE_ADMIN_SERVICE_HOST}}{{^DEVICE_ADMIN_SERVICE_HOST}}"localhost"{{/DEVICE_ADMIN_SERVICE_HOST}}
    port: {{DEVICE_ADMIN_SERVICE_PORT}}{{^DEVICE_ADMIN_SERVICE_PORT}}10020{{/DEVICE_ADMIN_SERVICE_PORT}}
{{/MOCK}}
{{#if MOCK}}
- descriptor: "device-admin:client:mock:default:1.0"
{{/if}}

# Service
- descriptor: "location-engine:service:default:default:1.0"

