---
# Container descriptor
- descriptor: "pip-services:context-info:default:default:1.0"
  name: "service-mqtt-listener"
  description: "MQTT listener service"

# Console logger
- descriptor: "pip-services:logger:console:default:1.0"
  level: "trace"

# Performance log counters
- descriptor: "pip-services:counters:log:default:1.0"

# MQTT ble-rssi listener
- descriptor: "mqtt-listener:listener:mqtt:ble-rssi:1.0"
  topic: "/ble/rssi"
  connection:
    uri:  {{MQTT_SERVICE_URI}}
    host: {{MQTT_SERVICE_HOST}}{{#unless MQTT_SERVICE_HOST}}"localhost"{{/unless}}
    port: {{MQTT_SERVICE_PORT}}{{#unless MQTT_SERVICE_PORT}}1883{{/unless}}
  credential:
    username: {{MQTT_USER}}
    password: {{MQTT_PASS}}
  options:
    autosubscribe: true


- descriptor: "mqtt-listener:publisher:nats:loc-raw-ble:1.0"
  subject: "loc-raw-ble"
  connection:
    uri:  {{NATS_SERVICE_URI}}
    host: {{NATS_SERVICE_HOST}}{{#unless NATS_SERVICE_HOST}}"localhost"{{/unless}}
    port: {{NATS_SERVICE_PORT}}{{#unless NATS_SERVICE_PORT}}4222{{/unless}}
  credential:
    username: {{NATS_USER}}
    password: {{NATS_PASS}}
  options:
    autosubscribe: true

# Service
- descriptor: "mqtt-listener:service:default:default:1.0"

