---
# Container descriptor
- descriptor: "pip-services:context-info:default:default:1.0"
  name: "device-admin"
  description: "device-admin microservice"

# Console logger
- descriptor: "pip-services:logger:console:default:1.0"
  level: "trace"

# Tracer that posts records to log
- descriptor: "pip-services:tracer:log:default:1.0"

# Performance counters that post values to log
- descriptor: "pip-services:counters:log:default:1.0"

{{#unless POSTGRES_ENABLED}}
# Memory persistence
- descriptor: "device-admin:persistence:memory:default:1.0"
{{/unless}}

{{#if POSTGRES_ENABLED}}
# PostgreSQL persistence
- descriptor: "device-admin:persistence:postgres:default:1.0"
  connection:
    uri: {{POSTGRES_SERVICE_URI}}
    host: {{POSTGRES_SERVICE_HOST}}{{#unless POSTGRES_SERVICE_HOST}}"localhost"{{/unless}}
    port: {{POSTGRES_SERVICE_PORT}}{{#unless POSTGRES_SERVICE_PORT}}5432{{/unless}}
    database: {{POSTGRES_DB}}{{#unless POSTGRES_DB}}"subterra-locate"{{/unless}}
  credential:
    username: {{POSTGRES_USER}}{{#unless POSTGRES_USER}}"postgres"{{/unless}}
    password: {{POSTGRES_PASSWORD}}{{#unless POSTGRES_PASSWORD}}"postgres"{{/unless}}
{{/if}}

# NATS device event publisher
- descriptor: "device-admin:publisher:nats:device-events:1.0"
  subject: "device.events"
  connection:
    uri:  {{NATS_SERVICE_URI}}
    host: {{NATS_SERVICE_HOST}}{{#unless NATS_SERVICE_HOST}}"localhost"{{/unless}}
    port: {{NATS_SERVICE_PORT}}{{#unless NATS_SERVICE_PORT}}4222{{/unless}}
  credential:
    username: {{NATS_USER}}
    password: {{NATS_PASS}}
  options:
    autosubscribe: true

# Service
- descriptor: "device-admin:service:default:default:1.0"

# Shared HTTP Endpoint
- descriptor: "pip-services:endpoint:grpc:default:1.0"
  connection:
    protocol: http
    host: 0.0.0.0
    port: {{DEVICE_ADMIN_PORT}}{{#unless DEVICE_ADMIN_PORT}}10020{{/unless}}

# Commandable GRPC V1
- descriptor: "device-admin:controller:grpc:default:1.0"
